<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Vectors-and-Matrices-in-Numpy---Lab" data-toc-modified-id="Vectors-and-Matrices-in-Numpy---Lab-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Vectors and Matrices in Numpy - Lab</a></span><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Objectives" data-toc-modified-id="Objectives-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Objectives</a></span></li><li><span><a href="#1.-Define-two-arrays-$A$--with-shape-$-(4-\times-2)$-and-$B$-with-shape-$(2-\times-3)$" data-toc-modified-id="1.-Define-two-arrays-$A$--with-shape-$-(4-\times-2)$-and-$B$-with-shape-$(2-\times-3)$-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$</a></span></li><li><span><a href="#2.-Print-the-dimensions-of-$A$-and-$B$" data-toc-modified-id="2.-Print-the-dimensions-of-$A$-and-$B$-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>2. Print the dimensions of $A$ and $B$</a></span></li><li><span><a href="#3.-Print-elements-from-$A$" data-toc-modified-id="3.-Print-elements-from-$A$-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>3. Print elements from $A$</a></span></li><li><span><a href="#4.-Write-a-routine-to-populate-a-matrix-with-random-data" data-toc-modified-id="4.-Write-a-routine-to-populate-a-matrix-with-random-data-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>4. Write a routine to populate a matrix with random data</a></span></li><li><span><a href="#5.-Turn-the-above-routine-into-a-function" data-toc-modified-id="5.-Turn-the-above-routine-into-a-function-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>5. Turn the above routine into a function</a></span></li><li><span><a href="#Summary" data-toc-modified-id="Summary-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Summary</a></span></li></ul></li></ul></div>

# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives

In this lab you will: 

- Find the shape of vectors and matrices 
- Access and manipulate individual scalar components of a matrix 
- Create vectors and matrices using Numpy and Python

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [2]:
# Code here
A = np.array([[1402, 191], [1371, 821], [949, 1437], [147,1448]])
B = np.array([[1, 2,3], [4, 5,6]])

## 2. Print the dimensions of $A$ and $B$ 

In [4]:
# Code here
print(A.shape, B.shape)

(4, 2) (2, 3)


## 3. Print elements from $A$

Print the following elements from $A$: 

* First row and first column
* First row and second column
* Third row and second column
* Fourth row and first column

In [12]:
# Code here
print(A[0,0])
print(A[0,1])
print(A[2,1])
print(A[-1,0])

1402
191
1437
147


## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10 

In [21]:
# Code here
C = [3,3]
C = np.zeros(C)
#M = np.zeros((3,3))

import random

# stackoverflow

# for x in range(0, rows):
#     for y in range(0, cols):
#         print a[x,y]

rows = C.shape[0]
cols = C.shape[1]

for x in range(0, rows):
    for y in range(0,cols):
        C[x][y] = random.randint(1,10)

print(C)

[[9. 7. 6.]
 [1. 2. 1.]
 [2. 9. 8.]]


## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero-valued matrices and fill with random data using the function
* Add the matrices together in Numpy 
* Print the results

In [25]:
# Code here
def fill(C):
    rows = C.shape[0]
    cols = C.shape[1]

    for x in range(0, rows):
        for y in range(0,cols):
            C[x][y] = random.randint(1,10)
    return C

matrix1 = np.zeros((4,4))
matrix2 = np.zeros((4,4))

matrix3 = fill(matrix1)
matrix4 = fill(matrix2)
#print(matrix3, matrix4)
matrix5 = matrix3 + matrix4
print(matrix5)

[[16. 16. 12.  7.]
 [12. 10. 12.  9.]
 [15. 12. 10. 11.]
 [12.  9. 14.  6.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in Numpy. We shall now move forward to learning more complex operations including dot products and matrix inversions.  